#Simulation preset saved by user
#Sat Jan 17 00:31:12 CET 2026
distanceRequiredToHeat=2
energyFromPlant=50
energyLossPerDay=6
energyToKid=25
energyToReproduce=50
genomeLength=10
mapHeight=15
mapWidth=15
maxMutations=3
minMutations=1
minTemperature=-10
plantsPerDay=2
seasonLength=50
startAnimalCount=20
startAnimalEnergy=100
startPlantCount=20
