#Simulation preset saved by user
#Sun Jan 18 21:24:37 CET 2026
distanceRequiredToHeat=2
energyFromPlant=50
energyLossPerDay=6
energyToKid=25
energyToReproduce=50
genomeLength=10
isSeasonal=true
mapHeight=15
mapWidth=15
maxMutations=3
minMutations=1
minTemperature=-10
plantsPerDay=5
seasonLength=50
startAnimalCount=20
startAnimalEnergy=100
startPlantCount=20
