#Simulation preset saved by user
#Mon Jan 19 12:10:46 CET 2026
distanceRequiredToHeat=2
energyFromPlant=50
energyLossPerDay=6
energyToKid=25
energyToReproduce=50
genomeLength=10
isSeasonal=true
mapHeight=40
mapWidth=40
maxMutations=3
minMutations=1
minTemperature=-10
plantsPerDay=5
seasonLength=50
startAnimalCount=20
startAnimalEnergy=500
startPlantCount=200
