#Simulation preset saved by user
#Tue Jan 20 16:01:07 CET 2026
distanceRequiredToHeat=2
energyFromPlant=50
energyLossPerDay=6
energyToKid=25
energyToReproduce=50
genomeLength=10
isSeasonal=true
mapHeight=100
mapWidth=100
maxMutations=3
minMutations=1
minTemperature=-10
plantsPerDay=50
seasonLength=50
startAnimalCount=1000
startAnimalEnergy=100
startPlantCount=1000
